---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hub-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - hub.openshift.io
  resources:
  - hubconfigs
  - spokeclusters
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hub.openshift.io
  resources:
  - hubconfigs/finalizers
  - spokeclusters/finalizers
  verbs:
  - update
- apiGroups:
  - hub.openshift.io
  resources:
  - spokeclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - update
